### ISSUE TITLE
Opentherm endpoint on hub v2 on new-ish firmwares

### ISSUE THREAD

**Issue by jacekowski** [msp1974/aioWiserHeatAPI#15]
Hi,

It looks like opentherm endpoint has moved on hub v2 on later firmwares ( 4.32.47 or newer) and is now located at /data/v2/openTherm/ instead of /data/v2/opentherm/ .

I'm not sure if new endpoint also works on v1 (i don't have v1 connected anymore).

**Comment by LGO44** [comment]
The diagnostic file given by a Hub V1 and a Hub V2 are the same for the OpenTherm as the 2 screen shots show
Hub V1
![image](https://github.com/user-attachments/assets/46298598-90bc-4dc4-92d9-450d8de3493b)


Hub V2 
![image](https://github.com/user-attachments/assets/ddbce62d-5d9d-4172-9201-2058dc3ef0f4)

**Comment by jacekowski** [comment]
Current endpoint just gives 404 on my hub.
![image](https://github.com/user-attachments/assets/5e906136-b230-40a4-8c19-578e7cf7f864)

**Comment by msp1974** [comment]
> The diagnostic file given by a Hub V1 and a Hub V2 are the same for the OpenTherm as the 2 screen shots show Hub V1 ![image](https://private-user-images.githubusercontent.com/95585425/376370970-46298598-90bc-4dc4-92d9-450d8de3493b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NDcxNDAsIm5iZiI6MTcyODk0Njg0MCwicGF0aCI6Ii85NTU4NTQyNS8zNzYzNzA5NzAtNDYyOTg1OTgtOTBiYy00ZGM0LTkyZDktNDUwZDhkZTM0OTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDIzMDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjI4NGU1M2IwMDdmNTg1MThhZmIzN2JjZDdiMDllM2EzYjNlMWY4YzJiNmMyNDVhYjEzNzZiM2Q5YWZlNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2tafHtHzpAkT2vI6sM5YAPfoFNcSEaNsFGLQLeHsIrw)
> 
> Hub V2 ![image](https://private-user-images.githubusercontent.com/95585425/376370685-ddbce62d-5d9d-4172-9201-2058dc3ef0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NDcxNDAsIm5iZiI6MTcyODk0Njg0MCwicGF0aCI6Ii85NTU4NTQyNS8zNzYzNzA2ODUtZGRiY2U2MmQtNWQ5ZC00MTcyLTkyMDEtMjA1OGRjM2VmMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDIzMDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NjJmNzVmNzhjMTI2MjdkZTVkOGMyM2NkMDdlMDA2YjNmN2ZhYjZkMzM5MzQxNzlmYmE3NTgyMDViZGRlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qbJcaIM9ZJRTDW73e3F8ynyJt-71Y-Ywd25P-GA35Vs)

If you don't have opentherm connected, the api will not read the endpoint, so will show empty in the diagnostic output.  Seems Hub v1 is still at the data/v2/opentherm endpoint.  @jacekowski , I will look if I can amend the endpoint if a v2 hub and firmware > 4.32.47.  Could you provide me a text output of the returned data so I can check it is the same and will therefore work.

**Comment by jacekowski** [comment]
It was working when i got the hub then few month ago opentherm data disappeared, then today i finally looked at the fault i tracked it down to endpoint being changed, data seems to be the same (i've modified my docker image to test and everything seems to work fine on new endpoint)

![image](https://github.com/user-attachments/assets/033afe40-dd2f-4f52-90fc-ad279d04607b)
`
{"CoprocessorUpdateFileName":"ManchesterCoPro.2.0.31.bin","CoprocessorUpdateStatus":"Success","chFlowActiveUpperSetpoint":800,"chFlowActiveLowerSetpoint":350,"dhwFlowSetpoint":550,"dhwEnable":true,"Enabled":true,"operatingMode":"OTplus","preDefinedRemoteBoilerParameters":{"dhwSetpointTransferEnable":true,"maxChSetpointTransferEnable":true,"dhwSetpointReadWrite":false,"maxChSetpointReadWrite":false,"dhwSetpointUpperBound":650,"dhwSetpointLowerBound":400,"dhwSetpoint":800,"maxChSetpoint":800,"maxChSetpointUpperBound":830,"maxChSetpointLowerBound":330},"ch1FlowSetpoint":350,"ch1FlowEnable":false,"ch2FlowSetpoint":350,"ch2FlowEnable":false,"operationalData":{"RelativeModulationLevel":0,"MinimumModulationLevel":25,"ChPressureBar":10,"DhwFlowRate":0,"Ch1FlowTemperature":381,"ChReturnTemperature":360,"MaximumCapacityKw":35,"SlaveStatus":0},"roomTemperature":227,"roomSetpoint":225,"TrackedRoomId":6,"CoprocessorVersion":"2.0.31","extendedDiagnostics":{"unsuccessfulBurnerStarts":10,"numberFlameSignalTooLow":13,"oemSpecificServiceCode":0,"successfulBurnerStarts":65535,"chPumpStarts":5794,"dhwPumpOrValveStarts":5243,"burnerStartsDuringDhwMode":7481,"burnerHours":243,"chPumpHours":5750,"dhwPumpOrValveHours":184,"burnerOnInDhwModeHours":86}}`

**Comment by msp1974** [comment]
@jacekowski, so I think I have fixed this in v1.5.16 of the api.  Would you be able to amend the version of the api in your manifest.json found in config/custom_components/wiser/manifest.json and see if it resolves it (you will need to restart HA for it to update).  This will be officially released in the next integration update which will bring you back inline.

**Comment by jacekowski** [comment]
It doesn't work. Seems like it is using old endpoint. 

my diagnostics (shortened to show relevant bits only) is showing the following:

```
  "integration_manifest": {
    "domain": "wiser",
    "name": "Drayton Wiser Integration for Home Assistant",
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "lovelace"
    ],
    "requirements": [
      "aioWiserHeatAPI==1.5.16"
    ],
  },
  "data": {
    "Domain": {
      "System": {
        "BoilerSettings": {
          "ControlType": "HeatSourceType_OpenTherm",
          "FuelType": "Gas",
          "CycleRate": "CPH_6",
          "OnOffHysteresis": 5
        },
        "ActiveSystemVersion": "4.36.33-9ad5712",
        "HardwareGeneration": 2,

```

**Comment by jacekowski** [comment]
It looks like the issue is with version.py, because my current version is "4.36.33-9ad5712", it fails >= check because 33 is smaller than 47

**Comment by msp1974** [comment]
Yes. Was doing late last night and realised when I saw your note I had cocked this up.  Will fix today and do a 1.5.17 release.  Sorry.

**Comment by jacekowski** [comment]
I've modified my docker image to fix version detection and it works with my fix, so that is the only issue with the change.

On another hand, any chance additional values from that endpoint could be made available (i'm not sure if it is just v2 thing), that is burner statistics and pump statistics

**Comment by msp1974** [comment]
> On another hand, any chance additional values from that endpoint could be made available (i'm not sure if it is just v2 thing), that is burner statistics and pump statistics

You'll have to provide me the data.  Unless you mean the extended diagnostics, in which case, I have added into the api for v1.5.17 and will add some sensors to the integration in an upcoming release.

**Comment by jacekowski** [comment]
Commit in dev branch covers everything.

**Comment by msp1974** [comment]
Great.  Will close.  v1.5.17 is now official release in v3.4.9 of the integration.
